### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by pwned4ever2** [CCW-Site/ccw-user-extension#31]
我是Senpai，这个链接udp和tcp应该问题不大。写这个模块的时候可以限制流量吧？我原来研究过一点ddos技术（僵尸网络，别来抓我）
主要是看西瓜的服务器怎么样。且西瓜服务器的保护一般tcpudp打不破的，主要看他是不是有bypass或者很大流量。有tcp和udp模块无伤大雅，还可以连api等。用西瓜的scratch平台不好做ddos工具，这个是可以放心的。希望能加tcp udp
———Senpai，极光工作室高管

**Comment by DannyDevPro** [comment]
az还没合并呢

**Comment by DannyDevPro** [comment]
az还没合并呢

**Comment by DannyDevPro** [comment]
az还没合并呢
