### ISSUE TITLE
便利模块记大过

### ISSUE THREAD

**Issue by Silverteal** [CCW-Site/ccw-user-extension#4]
[debug.zip](https://github.com/CCW-Site/ccw-user-extension/files/8689192/debug.zip)
如图。遍历模块导致v2参数取值异常

**Comment by sylarhcn** [comment]
遍历模块是指 便利积木吗

**Comment by sylarhcn** [comment]
感谢反馈，这个是 自定义返回值 积木的bug，已修复。
